[2024-12-26T19:10:23.618+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T19:10:23.671+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table manual__2024-12-26T19:10:01.047521+00:00 [queued]>
[2024-12-26T19:10:23.696+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table manual__2024-12-26T19:10:01.047521+00:00 [queued]>
[2024-12-26T19:10:23.697+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-26T19:10:23.731+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_create_original_table> on 2024-12-26 19:10:01.047521+00:00
[2024-12-26T19:10:23.765+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_create_original_table', 'manual__2024-12-26T19:10:01.047521+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmpm85c83ro']
[2024-12-26T19:10:23.780+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask step_create_original_table
[2024-12-26T19:10:23.794+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T19:10:23.797+0000] {standard_task_runner.py:72} INFO - Started process 267 to run task
[2024-12-26T19:10:23.868+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table manual__2024-12-26T19:10:01.047521+00:00 [running]> on host 9febbbbba9f2
[2024-12-26T19:10:24.062+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_create_original_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T19:10:01.047521+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T19:10:01.047521+00:00'
[2024-12-26T19:10:24.071+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T19:12:25.644+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-12-26T19:12:25.647+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T19:12:25.656+0000] {process_utils.py:132} INFO - Sending 15 to group 267. PIDs of all processes in the group: [267]
[2024-12-26T19:12:25.658+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 267
[2024-12-26T19:12:25.756+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-26T19:12:25.764+0000] {logging_mixin.py:190} INFO - Database connection closed.
[2024-12-26T19:12:25.808+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T19:12:25.872+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=267, status='terminated', exitcode=0, started='19:10:23') (267) terminated with exit code 0
