[2024-12-23T22:32:22.877+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T22:32:22.939+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table manual__2024-12-23T22:32:20.641063+00:00 [queued]>
[2024-12-23T22:32:22.959+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table manual__2024-12-23T22:32:20.641063+00:00 [queued]>
[2024-12-23T22:32:22.963+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-12-23T22:32:23.010+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_create_original_table> on 2024-12-23 22:32:20.641063+00:00
[2024-12-23T22:32:23.033+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_create_original_table', 'manual__2024-12-23T22:32:20.641063+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmpkfv98byu']
[2024-12-23T22:32:23.038+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask step_create_original_table
[2024-12-23T22:32:23.060+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=625) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T22:32:23.061+0000] {standard_task_runner.py:72} INFO - Started process 627 to run task
[2024-12-23T22:32:23.155+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table manual__2024-12-23T22:32:20.641063+00:00 [running]> on host 4774a7bd2972
[2024-12-23T22:32:23.401+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_create_original_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T22:32:20.641063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T22:32:20.641063+00:00'
[2024-12-23T22:32:23.403+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T22:32:23.556+0000] {logging_mixin.py:190} INFO - An error occurred: String.__init__() got an unexpected keyword argument 'nullable'
[2024-12-23T22:32:23.558+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-23T22:32:23.572+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T22:32:23.574+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NY_Pipeline_ETL_and_ML_Training, task_id=step_create_original_table, run_id=manual__2024-12-23T22:32:20.641063+00:00, execution_date=20241223T223220, start_date=20241223T223222, end_date=20241223T223223
[2024-12-23T22:32:23.609+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T22:32:23.635+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T22:32:23.651+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
